"""CRIB CORPUS for PK8/PK9/PK10, in the diary voice of the seven solved plaintexts.

Ranked: rank 1 = strongest prior (elapsed-time opener with a NOT-YET-USED number, or a
continuation of PK7's explicit "I will go home soon"); rank 3 = plausible but generic.

Openings: four of seven solved puzzles open with an elapsed-time marker
(SEVENTHMONTH / TWOYEARSIN / FOURTEENDAYSIN / THREEWEEKSIN).  Numbers already spent:
EIGHT TWELVE SEVEN SEVENTH FIFTEEN SIX TWO FOURTEEN TEN THREE FOUR -> prefer the rest.
Closings: PK1 "...ALLFAILED", PK3 "...NOANSWERCAMEIWROTEAGAIN", PK7 "...WILLGOHOMESOON".
Phrases: recurring nouns that can sit anywhere in the text.
"""
NEW_NUM  = ['ONE','FIVE','NINE','ELEVEN','THIRTEEN','TWENTY','THIRTY','FORTY','FIFTY',
            'AHUNDRED','ONEHUNDRED','TWENTYONE','SIXTEEN','SEVENTEEN','EIGHTEEN','NINETEEN']
OLD_NUM  = ['TWO','THREE','FOUR','SIX','SEVEN','EIGHT','TEN','TWELVE','FOURTEEN','FIFTEEN']
NEW_ORD  = ['NINTH','ELEVENTH','TWELFTH','THIRTEENTH','TWENTIETH','FIRST','SECOND','FIFTH','LAST']
OLD_ORD  = ['SEVENTH','EIGHTH','TENTH','THIRD','FOURTH','SIXTH']
UNIT     = ['DAYS','WEEKS','MONTHS','YEARS','WINTERS','SUMMERS','NIGHTS','MORNINGS','SEASONS']
UNIT_S   = ['MONTH','YEAR','WEEK','DAY','WINTER','SUMMER']
TAIL     = ['IN','INTHEBARN','INTHEWORKSHOP','INTHEARCHIVE','ATTHEBENCH','ATTHEFORGE',
            'HOMEAGAIN','SINCEILEFT','AFTERIRETURNED','ANDIAMHOME','HAVEPASSED','PASSED',
            'UNDERTHEWHITESMITH','WITHTHEWHITESMITH','ONTHEROAD','OFSILENCE','OFWAITING',
            'OFWORK','LATER','AFTER','SINCE','ANDSTILLNOWORD','ANDNOTHING','ATHOME',
            'INWERISEBEFORETHESUN','INTHEHOUSEOFTHEWHITESMITH','BACKINTHEARCHIVE',
            'ATTHEBENCHANDMYHANDS','SINCETHEINNERDOOROPENED','SINCEISAWTHENEEDLE']
ORD_TAIL = ['MONTHIWROTETO','MONTHI','YEARI','YEARINTHEARCHIVE','WEEKI','DAYI',
            'MONTHIRETURNED','YEARIRETURNEDTO','ENTRYINTHELOG','MONTHATTHEBENCH',
            'WINTERINTHEWORKSHOP','MONTHOFTHEAPPRENTICESHIP']
LIT_OPEN = [
 'INVESTIGATIONLOGITEMNINE','INVESTIGATIONLOGITEMTEN','INVESTIGATIONLOGITEMELEVEN',
 'INVESTIGATIONLOGITEMNUMBERNINE','ACCESSIONLOGITEMNINE',
 'IHAVERETURNEDTOTHEARCHIVE','IHAVECOMEHOMETOTHEARCHIVE','IAMHOMEAGAINANDTHEARCHIVE',
 'IHAVEBEENHOMEFORAYEARNOW','IWENTHOMEASISAIDIWOULD','WHENIRETURNEDTOTHEARCHIVE',
 'THEWHITESMITHISDEADANDI','THEWHITESMITHDIEDINTHEWINTER','THEWHITESMITHLETMEGO',
 'THENEEDLEISINMYPOSSESSION','THENEEDLEISMINEATLAST','IHAVETHENEEDLEATLAST',
 'IHAVEUNRAVELEDTHEKNOT','THEKNOTISUNRAVELEDATLAST','THEKNOTCAMEAPARTINMYHANDS',
 'IHAVEFOUNDTHELOSTARCHIVE','THELOSTARCHIVEOFPELLEGRIN','IHAVESEENTHELOSTARCHIVE',
 'BEHINDTHEINNERDOORTHEREIS','THEINNERDOOROPENEDONTO','THEINNERDOORLEDTO',
 'IAMTHETHIRTEENTHARCHIVIST','THIRTEENPRIORARCHIVISTSTRIED','IAMNOLONGERANAPPRENTICE',
 'MYHANDSAREMYOWNAGAIN','MYHANDNOLONGERFALTERS','THISISTHELASTENTRYINTHELOG',
 'THISISMYLASTENTRY','THISISTHEFINALENTRY','IWROTETOTHEARCHIVEINBERN',
 'IHAVEMADEONENEEDLEOFMYOWN','ONEOFMYOWNMAKINGATLAST','THETHREADINSCRIBEDWITHLETTERS',
 'THEROUTETOTHELOSTARCHIVE','THEACCESSIONLOGSAYSTHAT','IREADTHEACCESSIONLOGAGAIN',
 'IHAVEBEGUNTOWORKAGAIN','IBEGANAGAINATTHEBENCH','TENYEARSUNDERTHEWHITESMITH',
]
LIT_CLOSE = [
 'ANDWILLGOHOMESOON','ANDIWILLGOHOMESOON','ANDSOIWENTHOME','ANDIWENTHOME',
 'ANDIHAVEMADEPEACEWITHIT','IHAVEMADEPEACEWITHITATLAST','ALLFAILED','THEYALLFAILED',
 'NOANSWERCAMEIWROTEAGAIN','NOANSWERHASCOME','NOANSWERCAME','ANDNOANSWERCAME',
 'ANDOPENEDTHEINNERDOOR','ANDHEOPENEDTHEINNERDOOR','ANDTHEINNERDOOROPENED',
 'ONEOFMYOWNMAKING','TAKEONEOFMYOWNMAKING','HEWILLLETMETAKEONEOFMYOWNMAKING',
 'THERESIDUEOFHISPRACTICE','THEONLYRESIDUEOFHISPRACTICE','ANDLOSTCOUNTLONGAGO',
 'ANDIWILLBEGINAGAIN','IWILLBEGINAGAINTOMORROW','ANDIBEGINAGAIN',
 'IWILLWRITEAGAINWHENIKNOWMORE','IWILLWRITEWHENIKNOWMORE','MOREWHENIKNOWIT',
 'THEARCHIVEISMINE','ANDTHEARCHIVEISMINE','THEARCHIVEISCOMPLETE',
 'ANDTHEKNOTISUNRAVELED','THEKNOTISUNRAVELED','THETHREADISREADATLAST',
 'ANDIAMPATIENT','IAMPATIENT','IAMPATIENTSTILL','ANDSTILLIWAIT','ANDIWAIT',
 'THISISNOTMYCALLING','ITISNOTMYCALLING','ANDTHATISENOUGH','ITISENOUGH',
 'ANDNOTHINGMORE','NOTHINGMORE','ANDTHATISALL','THATISALL','ANDHEREITENDS',
 'ANDTHEWORKISDONE','THEWORKISDONE','ANDMYWORKISDONE','ANDIRESTATLAST',
 'INTOTHECASEANDCLOSEDIT','IPLACEDTHENEEDLEINTHECASE','ANDLOCKEDTHECASE',
 'ANDIWILLNOTRETURN','IWILLNOTRETURN','ANDINEVERSAWHIMAGAIN','INEVERSAWHIMAGAIN',
 'ANDTHELOGISCLOSED','THELOGISCLOSED','ANDSOTHELOGENDS',
]
PHRASE = [
 'THEWHITESMITH','THEWHITESMITHSAYS','THEWHITESMITHTOLDME','THEWHITESMITHSWORKSHOP',
 'THELOSTARCHIVE','THEARCHIVEOFPELLEGRIN','THELOSTARCHIVEOFPELLEGRIN','PELLEGRIN',
 'THEACCESSIONLOG','THEINNERDOOR','THENEEDLE','THEKNOT','THETHREAD','THEBARN',
 'THEWORKSHOP','THEGUTTERALONGTHEWALL','EXQUISITENEEDLES','ANEEDLEFINEENOUGH',
 'FINEENOUGHTOSPLITAHAIR','ORPIERCEGLASS','PURIFYINGHISMETAL','AFINEWIRE',
 'DRAWINGITINTOAFINEWIRE','INTHEMANNEROFANARCHIVIST','WINTERFODDER','ASTONEBARN',
 'HISALPINEWORKSHOP','ONTHEROADTOHISWORKSHOP','THEOLDTOOLSOFHISTRADE',
 'UNAGOTANTOSOTTILE','DALEGGEREQUALUNQUENODO','UNAGOTANTOSOTTILEDALEGGERE',
 'QUALUNQUENODO','PELLEGRINSOWNHAND','WRITTENINPELLEGRINSOWNHAND',
 'TWELVEPRIORARCHIVISTS','ONCEUNRAVELEDITREVEALS','ITSTHREADINSCRIBED',
 'IFISTUDYUNDERHIMFORTENYEARS','HEMAKESONEEVERYDAY','THERESIDUEOFHISPRACTICE',
 'IAMPATIENTBUTIKNOW','THISISNOTMYCALLING','IHAVEMADEPEACEWITHIT',
 'THEMOSTINTRIGUING','AMARGINALCOMMENT','MARGINALIA','ATREATISEONTEXTILES',
 'AVIENNESEANATOMIST','ASURGICALDEMONSTRATION','INBERN','INVIENNA','INTHEALPS',
 'THEROUTETOTHELOSTARCHIVE','THEACCESSIONLOGSAYS','MYHANDFALTERS','MYHANDS',
 'BEFORETHESUN','BYNOON','EVERYDAYANDLOSTCOUNT','ONEOFHISNEEDLES','ISHIDDENINTHEBARN',
 'IHAVEBEGUNTOWORK','ANDHETOOKITFROMME','ITDREWNOBLOOD','PRICKMYFINGER',
 'THEWHITESMITHBROUGHTFOODANDWATER','BUTNOCOUNSEL','LIFTINGEACHBALE',
 'EXAMININGTHESTRAWSINROWS','ONTOACLOTH','THEGATES','HEMETMEATTHEGATES',
 'HISPERFUNCTORYLETTERS','IREREADHISLETTERS','ACRAFTSMANNAMED','THENEEDLESTRAIL',
]

def _ranked():
    out = {}                                   # crib -> (rank, kind)
    def add(s, r, k):
        if 12 <= len(s) <= 64:
            if s not in out or r < out[s][0]: out[s] = (r, k)
    # rank-1 openings: unused number + unit + tail
    for n in NEW_NUM:
        for u in UNIT:
            for t in TAIL: add(n+u+t, 1, 'open')
    for n in OLD_NUM:
        for u in UNIT:
            for t in TAIL[:14]: add(n+u+t, 2, 'open')
    for o in NEW_ORD:
        for t in ORD_TAIL: add(o+t, 1, 'open')
    for o in OLD_ORD:
        for t in ORD_TAIL: add(o+t, 2, 'open')
    for n in NEW_NUM+OLD_NUM:
        for u in UNIT_S: add(n+u+'LATER', 2, 'open')
    for s in LIT_OPEN: add(s, 1, 'open')
    for s in LIT_CLOSE: add(s, 1, 'close')
    for s in PHRASE:   add(s, 1, 'phrase')
    return out

def corpus(max_open=260, max_close=160, max_phrase=140):
    r = _ranked()
    op = sorted([s for s in r if r[s][1]=='open'],  key=lambda s:(r[s][0], -len(s), s))[:max_open]
    cl = sorted([s for s in r if r[s][1]=='close'], key=lambda s:(r[s][0], -len(s), s))[:max_close]
    ph = sorted([s for s in r if r[s][1]=='phrase'],key=lambda s:(r[s][0], -len(s), s))[:max_phrase]
    return ([(s, r[s][0], 'open') for s in op] + [(s, r[s][0], 'close') for s in cl]
            + [(s, r[s][0], 'phrase') for s in ph])

if __name__ == '__main__':
    from collections import Counter
    C = corpus()
    print(f"corpus {len(C)}  kinds {Counter(k for _,_,k in C)}  ranks {Counter(r for _,r,_ in C)}")
    print("len hist", dict(sorted(Counter(len(s) for s,_,_ in C).items())))
    for k in ('open','close','phrase'):
        ex = [s for s,_,kk in C if kk==k][:4]
        print(f"  {k}: {ex}")
