"""Paradigm Kryptos CTF harness. Ground truth: PK_CONTEXT.md sections 1,2,5."""
import numpy as np
from math import gcd, lcm

KA = "KRYPTOSABCDEFGHIJLMNQUVWXZ"
AZ = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
KAI = {c: i for i, c in enumerate(KA)}
AZI = {c: i for i, c in enumerate(AZ)}

CT = {
'pk1':"MQRALWVSJIMSXGJSVWQPHJMDINKXGIMHNKYUTXTTGJCYIABTJUMQEOFBITNBMONGVWETDLAIJPQYMZIKBQVRXZHUIJVDJLTQHIQYHEQKFTPTJYCONAFXYWQIBONAYXGWJFFIQMVXNVQYQFMWKFEJQYZFBWKXBKDQLJRELWGWDKHECRSFBKOVQJCPYDNKXYHE",
'pk2':"HNETIOCOIOISNNENEELOWYTTLQUBDBTHTEOTRRASAHCDSEETONVRCESHRRETUPCITEWIGNIUNIGANLHJRAHMSRUINHERAEEAEAJEEEEKEEDATIIAONIXRNRHCNTLGLOIIUNSEESEGNBANTVTCSFREDIUROTNENHMRIIEROLTLSDAOOAEQIEOAPUHITHAIKHTIEUHGSLAFFSNVRSRHNNSMASTIPIAHAOEEUDESSOEONCDHAOTOOEOTSEECLADNHNTOUVSGAGTATSNEWHSATEUEETEURTRNEOGITREHMPPROBEOETOERICETGSMTEITENNSGSDRNOVTTFBTTATMLOSOPLSTARATE",
'pk3':"HWZTRPPVHZLHRBQBQOMZBACNOTHLYGBATBTKHERQHRVZWWXCTZLRRVZCROHCIOTBVJKCALNKFJHEIMKUHJPFNVBCGQYNZMOHGBUTDPTJTDSUBOLYPLSKIEMANXMFNDBCTNRTLLVQOXUBPAXQUVDNXUMCIFOGETZWHJDIWDBWQFXAOMWBBCQXYZFZBTRIQMYOFFMVWSFLPTHFFQUINGLAMSQJOPUESPIQGZZCTJVRLQMIIRROOGBWNPQMXFQDVFTCVGNRIXQKUYYKBRTWPCDHLAWC",
'pk4':"YOVISYUAFKUQNRJQLZTAZTMQOUKELJKCYUWIDSPSWRJRUEZNIFPUMUHQFFVBGOBEPWNTZGKVUTOVFSADUJUAYGWKQYOGNKHZVQMEWHSJGJFOBPHXKAPEXPWRJTSPSIJLCSXYTLDFBNZNPUAZNBZPKRFCUZDDZHZULZVPVWCXSIUVSCCFATGSJPNIGCJVTMUPTCGRTOFRXWCYKOMXOJKCECRUCKBDCIYJ",
'pk5':"IJQUVJJINKWMJBNJHKZZMTVTUBFHXZJIUHOVONZNXKFUALEMYWTNNNILTRNVSXIXIQCLOSFZVZGTHQKZFJJHJMJTSEPAMKNMTGPVFWSWSBSIHOJWNFXDIJPJNOVBWWXJYUVVAFTIDZISJNCIGHXKLNFEQRDVYIXUXQIZFNXAKYXIUEVGRBMHWRFDZSMMDPMKIZNUQUJNXVZTGHCNAUVIYZCLRAVMJKAOIBOPZTJUPACSTFFLERTGBFFNCYTAVIRXXYOXHCDWHWWKAMQO",
'pk6':"BXFIVOAJFNMLKEVEHDFJQCMVLMGNVOHCJNBOAEVRRWIJFMCWMNOOMMOSRNKYOCFRYWKHBNMYCYHDECQCFNTOXNOBKBHWBOMNHFIIZDBJRNXBABFRCBLIIBLDCINOHNLXSBKVMSBNVOFVNBFYDJEVUGMNOBMLCQACBLGNABEBCJXBEYUIBDTFOSOULYCQHBXUHSEYMCBJIIHWDCFSEVLDMMUOVFADHUMKXCGUCQIRGBCEIJFYIXOEJYHDJHMXTDIEXNDAFBMOJMYAEYBVYNFSCXBWNYOVFDXDHWFCERDEBWZUKDIJTUGCJMMVQII",
'pk7':"FNRHTKRHSEDEJMBOWBDSCSDDXLICXULMBYQXWTGUIVNDYZBEQLVHFFFIDAKDCCJKWGOOUESCYELYMRAKIUJCUSEAXUQTYKOBVYDYMRBYWOTQEESCQSMDYDQJNPSWRSUOFMFJDYXSHCXNHVJVBYMZOZOATHTEOVLOQWZITHTEAFMKGLASTBZRDMFRJPKWJOXZXPJCBOVAZEPKAEJPPSIUJODXTXERWTLTTYMRENBJGTNMLBDJMYJDDLRCXCQCHYMJMHBEOLXEUFNJKBPRSHTEYXB",
'pk8':"COPVEJJVSVURTVIPYOTPLHGBTMAUCCPESIWIGZBWSJPKTRPUEKQFIFCLHMXTHIMHWOYIGURBOMPARCVXVKBDDVBVHDRHGCVNWWVLBMYWMWHICFIXZWBVZYCQGNOGJGUMLNPUTHQCXNWPQZOIRJZGSWVPY",
'pk9':"KSYAWFEYYOISZGEUFBLYATAIBYFAQBQYYVDWJKLJXMYIEPIFVHPQNHZGSUHUUDXLEHRHUMALHEGLHXSJMUXGNUIVBXGUJHZRZGUSVHMLSCTSUQXHSUMQQIFUQGKHJGUQGLHDKEWSKAMHIJXD",
'pk10':"UBINFYJSFQXQVRLJJAJDGBXIWKDMAREZTGSHQWRXCHEPCLYSDNGYRRBTCVOZJYVLYWREJTCDOYVEYCJJVZKRMKTRPGVHRWMJSRCSHXZMJEVQKJYJJAYZKDFQBGRSWXATJMEXKFXAXKSIZXOERFESNVCGCNRHEOBCNCBUPXTJJRCIMDMRUVZWRDRRFXAPGPIGSPLILFIZSTDZYOVQGGDFUFZPUOJPJVWREUVRQIYPCEHGYUZUKWTFXELUNOKBANZFTFRMXZSXXQSBGPCWGXPFSCANSVUYLMTZIRCCCJJPBQAEPWVCDIMLOPOXQEGJKVQIVHEFAPQMVCYSQAFKCTYTPAOOJZCWIPGDPAFTINBFFHVXYEQXCEIDJJOUABBAHSWKHGMLJBXDSQEFBBDLTLJPLZPIPPTRGDRZIZPUPYJODOCSOYCZZWTKYWMBQTFMFEQZWVPQYLJTMEYKYBNOPEPUMHCFJSLFWOISWLKFFABTYFQDTEQBDELIEOZQ",
}

PT = {
'pk1':"INVESTIGATIONLOGITEMEIGHTKNOTTIGHTLYWOUNDITSTHREADINSCRIBEDWITHLETTERSTHEACCESSIONLOGSAYSONCEUNRAVELEDITREVEALSTHEROUTETOTHELOSTARCHIVEOFPELLEGRINTWELVEPRIORARCHIVISTSTRIEDTOUNRAVELITALLFAILED",
'pk2':"IHAVEFOUNDREFERENCESTOTHEKNOTINSEVENOTHERRECORDSINOURARCHIVETHEMOSTINTRIGUINGISAPASSINGCOMMENTINATREATISEONTEXTILESWRITTENINPELLEGRINSOWNHANDWHICHSAYSUNAGOTANTOSOTTILEDALEGGEREQUALUNQUENODOIBELIEVEDTHISTOBEJUSTATURNOFPHRASEBUTTHEOTHERMENTIONSSCATTEREDTHROUGHMARGINALIAINBOOKSTHATSHARENOOTHERTOPICHAVELEDMETOSUSPECTTHEPASSAGEREFERSTOAREALOBJECTANEEDLE",
'pk3':"SEVENTHMONTHIWROTETOFIFTEENCORRESPONDENTSINSIXCOUNTRIESSEEKINGANYWORDOFTHEITEMMOSTKNEWNOTHINGAFEWHADHEARDLEGENDSOFANEEDLEFINEENOUGHTOSPLITAHAIRORPIERCEGLASSATLASTAVIENNESEANATOMISTSAIDHESAWSUCHANINSTRUMENTUSEDATASURGICALDEMONSTRATIONINBERNIWROTETOHISADDRESSNOANSWERCAMEIWROTEAGAIN",
'pk4':"TWOYEARSINTHENEEDLESTRAILLEDMETOACRAFTSMANNAMEDTHEWHITESMITHONTHEROADTOHISALPINEWORKSHOPIREREADHISPERFUNCTORYLETTERSHEMETMEATTHEGATESANDLEDMETOASTONEBARNSTACKEDWITHWINTERFODDERONEOFHISNEEDLESISHIDDENINTHEBARNIHAVEBEGUNTOWORK",
'pk5':"FOURTEENDAYSINTHEBARNIWORKEDINTHEMANNEROFANARCHIVISTLIFTINGEACHBALEONTOACLOTHANDEXAMININGTHESTRAWSINROWSTHEWHITESMITHBROUGHTFOODANDWATERBUTNOCOUNSELTHISMORNINGIFELTTHENEEDLEPRICKMYFINGERSOFINETHATITDREWNOBLOODICARRIEDITTOTHEWHITESMITHANDHETOOKITFROMMEANDOPENEDTHEINNERDOOR",
'pk6':"THEWHITESMITHSWORKSHOPISFILLEDWITHTHEOLDTOOLSOFHISTRADEMYEYESAREDRAWNTOTHEGUTTERALONGTHEWALLWHICHISSTREWNWITHEXQUISITENEEDLESTHEWHITESMITHSAYSHEMAKESONEEVERYDAYANDLOSTCOUNTLONGAGOIASKWHATHEDOESWITHTHEMANDHESAYSTHEYAREONLYTHERESIDUEOFHISPRACTICEHETELLSMETHATIFISTUDYUNDERHIMFORTENYEARSHEWILLLETMETAKEONEOFMYOWNMAKING",
'pk7':"THREEWEEKSINWERISEBEFORETHESUNANDEACHNEEDLEISDONEBYNOONTHEWHITESMITHSHOWSMEHISTECHNIQUEFORPURIFYINGHISMETALBEFOREDRAWINGITINTOAFINEWIREHEHASMEREPEATTHESAMESTEPFOURTIMESWITHSLIGHTVARIATIONSSTILLMYHANDFALTERSIAMPATIENTBUTIKNOWTHISISNOTMYCALLINGIHAVEMADEPEACEWITHITANDWILLGOHOMESOON",
}

# ---------------- columnar transposition ----------------
def col_enc(pt, perm):
    W = len(perm)
    cols = [pt[c::W] for c in range(W)]
    return ''.join(cols[c] for c in perm)

def col_dec(ct, perm):
    W = len(perm); n = len(ct)
    lens = [len(range(c, n, W)) for c in range(W)]
    cols = [None]*W; pos = 0
    for c in perm:
        cols[c] = ct[pos:pos+lens[c]]; pos += lens[c]
    out = []
    idx = [0]*W
    for i in range(n):
        c = i % W
        out.append(cols[c][idx[c]]); idx[c] += 1
    return ''.join(out)

# ---------------- Quagmire III (additive on KA) ----------------
def q3enc(t, keys, alpha=KA, keyalpha=None):
    ka = keyalpha or alpha
    ai = {c: i for i, c in enumerate(alpha)}
    ki = {c: i for i, c in enumerate(ka)}
    out = []
    for i, ch in enumerate(t):
        s = sum(ki[k[i % len(k)]] for k in keys)
        out.append(alpha[(ai[ch] + s) % 26])
    return ''.join(out)

def q3dec(t, keys, alpha=KA, keyalpha=None):
    ka = keyalpha or alpha
    ai = {c: i for i, c in enumerate(alpha)}
    ki = {c: i for i, c in enumerate(ka)}
    out = []
    for i, ch in enumerate(t):
        s = sum(ki[k[i % len(k)]] for k in keys)
        out.append(alpha[(ai[ch] - s) % 26])
    return ''.join(out)

# ---------------- numeric helpers ----------------
def to_idx(s, alpha=KA):
    ai = {c: i for i, c in enumerate(alpha)}
    return np.array([ai[c] for c in s], dtype=np.int8)

def to_str(a, alpha=KA):
    return ''.join(alpha[int(v) % 26] for v in a)

def ioc(s):
    """Index of coincidence, normalized to 26 (English ~0.0647, random 0.0385)."""
    if isinstance(s, str):
        a = np.frombuffer(s.encode(), dtype=np.uint8)
    else:
        a = np.asarray(s)
    n = len(a)
    if n < 2: return 0.0
    cnt = np.bincount(a.astype(np.int64), minlength=256)
    return float((cnt * (cnt - 1)).sum()) / (n * (n - 1))

def ioc_rows(R):
    """Vectorized IoC for each row of an int array R (values 0..25)."""
    R = np.asarray(R)
    N, L = R.shape
    if L < 2: return np.zeros(N)
    cnt = np.zeros((N, 26), dtype=np.int32)
    for x in range(26):
        cnt[:, x] = (R == x).sum(axis=1)
    return (cnt.astype(np.float64) * (cnt - 1)).sum(axis=1) / (L * (L - 1))

# ---------------- quadgram model ----------------
_QG = None
def load_quadgrams(path='quadgrams.npy'):
    global _QG
    if _QG is None:
        _QG = np.load(path)
    return _QG

def qscore(s, qg=None):
    """log10 probability per letter. English ~ -4.2 (A-Z ordered text)."""
    qg = qg if qg is not None else load_quadgrams()
    if isinstance(s, str):
        a = np.array([AZI[c] for c in s], dtype=np.int64)
    else:
        a = np.asarray(s, dtype=np.int64)
    if len(a) < 4: return -99.0
    k = a[:-3]*17576 + a[1:-2]*676 + a[2:-1]*26 + a[3:]
    return float(qg[k].mean())

def qscore_rows(R, qg=None):
    qg = qg if qg is not None else load_quadgrams()
    R = np.asarray(R, dtype=np.int64)
    k = R[:, :-3]*17576 + R[:, 1:-2]*676 + R[:, 2:-1]*26 + R[:, 3:]
    return qg[k].mean(axis=1)

def ka_to_az(s):
    """Re-map a KA-indexed string into A-Z index space for quadgram scoring."""
    return ''.join(AZ[KAI[c]] for c in s)
